app/imanager/forms.py
# -*- coding:utf-8 -*-
from flask_wtf import Form
from flask_login import current_user
from wtforms import StringField, PasswordField, BooleanField, SubmitField, SelectField
from wtforms.validators import Required, Length, Email, Regexp, EqualTo
from wtforms import ValidationError
from ..models import iManagerItem


class ItemRegistrationForm(Form):
    item_id = StringField('事件名称', validators=[
                          Required(message='请输入事件名称'), Length(1, 32)])
    item_name = StringField(
        '事件内容', validators=[Required(message='请输入事件内容'), Length(1, 64)])
    angle_range = SelectField('优先级', coerce=int)
    submit = SubmitField('提交事件')

    def validate_item_id(self, field):
        if iManagerItem.query.filter_by(item_id=field.data).first():
            raise ValidationError('该事件名称被其他人注册啦！')

    def __init__(self, *args, **kwargs):
        super(ItemRegistrationForm, self).__init__(*args, **kwargs)
        self.angle_range.choices = [(1, '优先级1'), (2, '优先级2'), (3, '优先级3'), 
                            (4, '优先级4'), (5, '优先级5')]

class EditItemForm(Form):
    item_id = StringField('物品ID', validators=[
                          Required(message='请输入事件名称'), Length(1, 32)])
    item_name = StringField('物品名称', validators=[
                          Required(message='请输入事件内容'), Length(1, 64)])
    angle_range = SelectField('警戒范围', coerce=int)
    alarm_state = BooleanField('事件已完成')
    submit = SubmitField('提交事件')

    def validate_item_id(self, field):
        imanager = iManagerItem.query.filter_by(item_id=field.data).first()
        if imanager and imanager.owner != current_user:
            raise ValidationError('该事件名称被其他人注册啦！')

    def __init__(self, item, *args, **kwargs):
        super(EditItemForm, self).__init__(*args, **kwargs)
        self.item = item
        self.angle_range.choices = [(1, '优先级1'), (2, '优先级2'), (3, '优先级3'), 
                            (4, '优先级4'), (5, '优先级5')]
        

app/imanager/__init__.py
from flask import Blueprint

imanager = Blueprint('imanager', __name__)

from . import views, forms, error
from ..models import Permission

@imanager.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)

app/imanager/views.py
from flask import render_template, redirect, request, url_for, flash, abort
from flask_login import login_user, logout_user, login_required, \
    current_user
from . import imanager
from .. import db
from ..decorators import admin_required
from ..models import User, Permission, iManagerItem
from ..email import send_email
from .forms import ItemRegistrationForm, EditItemForm


@imanager.route('/itemregistrate', methods=['GET', 'POST'])
@login_required
@admin_required
def itemregistrate():
    form = ItemRegistrationForm()
    if form.validate_on_submit():
        imanager = iManagerItem(item_id=form.item_id.data,
                                 item_name=form.item_name.data,
                                 angle_range=form.angle_range.data,
                                 owner=current_user._get_current_object())
        db.session.add(imanager)
        flash('成功添加 ' + form.item_name.data + ' 到您的记事本中')
        return redirect(url_for('imanager.itemboard'))
    return render_template("imanager/itemregistrate.html", form=form)


@imanager.route('/itemboard', methods=['GET', 'POST'])
@login_required
def itemboard():
    user = current_user
    items = user.imanagers.order_by(iManagerItem.registe_time)
    return render_template('imanager/itemboard.html', user=user, items=items)


@imanager.route('/edit-item/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_item(id):
    user = current_user
    item = iManagerItem.query.get_or_404(id)
    if user != item.owner:
        flash('你没有该事件的编辑权限！')
        return redirect(url_for('imanager.itemboard', username=user.username))
    form = EditItemForm(item=item)
    if form.validate_on_submit():
        item.item_id = form.item_id.data
        item.item_name = form.item_name.data
        item.alarm_state = form.alarm_state.data
        item.angle_range = form.angle_range.data
        db.session.add(item)
        flash('成功更新事件信息')
        return redirect(url_for('imanager.itemboard', username=user.username))
    form.item_id.data = item.item_id
    form.item_name.data = item.item_name
    form.alarm_state.data = item.alarm_state
    form.angle_range = item.angle_range
    return render_template('imanager/edit_item.html', form=form)


@imanager.route('/delete-item/<int:id>', methods=['GET', 'POST'])
@login_required
def delete(id):
    user = current_user
    item = iManagerItem.query.get_or_404(id)
    if current_user == item.owner:
        db.session.delete(item)
        flash('成功删除事件')
        return redirect(url_for('imanager.itemboard', username=user.username))
    return render_template('.index.html')

app/templates/imanager/_items.html
<ul>
    {% for item in items %}

    <li>事件ID：{{ item.id }} 丨 名称：{{ item.item_id }} 丨 内容：{{ item.item_name }} 丨 添加时间： {{ item.registe_time }}</br> 优先级： {{ item.angle_range }} 丨 所有者ID：{{ item.owner_id }} 丨 完成状态：{{ item.alarm_state }}
        <div class="post-footer">
            <a href="{{ url_for('imanager.edit_item', id=item.id) }}">
                <span class="label label-primary">编辑</span>
            </a>
            <a href="{{ url_for('imanager.delete', id=item.id) }}">
                <span class="label label-danger">删除</span>
            </a>
        </div>
    </li>
    {% endfor %}
</ul>

app/templates/imanager/edit_item.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% set active_page = "edit_item" %}
{% block title %}Simian CI - 编辑物品{% endblock %}

{% block page_content %}
    <h1 class="lead-title text-center text-lg-left">Simian CI - EDIT ITEMS</h1>
    <p class="lead-subtitle text-center text-lg-left">编辑您的个人信息</p>

    <div class="col-md-4" >
        {{ wtf.quick_form(form) }}
    </div>
{% endblock %}

{% block page_content2 %}
    <h1 class="lead-title text-center text-lg-left">Simian CI - EDIT ITEMS</h1>
    <p class="lead-subtitle text-center text-lg-left">编辑您的个人信息</p>

    <div class="col-md-4" >
        {{ wtf.quick_form(form) }}
    </div>
{% endblock %}

app/templates/imanager/itemboard.html
{% extends "base.html" %}
{% set active_page = "index" %}
{% block title %}Simian CI - 信息管理{% endblock %}
{% block page_content %}
    <div id="features" class="features-section">
        
        <div class="container text-center">
            <h2 class="section-title">{{ user.username }} 的记事本</h2>
            <p class="intro">{% if user.name %}{{ user.name }}<br>{% endif %}</p>
            {% if user.about_me %}
            <p class="intro">关于我： {{ user.about_me }}</p>
            {% endif %}
            <p class="intro">最后一次登陆： {{ moment(user.last_seen).fromNow() }}.</p>
            <div class="tabbed-area row">
                <!-- Nav tabs -->
                <div style="text-align: center">
                    {% include 'imanager/_items.html' %}
                </div>
            </div><!--//tabbed-area-->

        </div><!--//container-->
    </div><!--//features-->
{% endblock %}

{% block page_content2 %}
    <div id="features" class="features-section">
        
        <div class="container text-center">
            <h2 class="section-title">{{ user.username }} 的记事本</h2>
            <p class="intro">{% if user.name %}{{ user.name }}<br>{% endif %}</p>
            {% if user.about_me %}
            <p class="intro">{{ user.about_me }}</p>
            {% endif %}
            <p class="intro">最后一次登陆： {{ moment(user.last_seen).fromNow() }}.</p>
            <div class="tabbed-area row">
                <!-- Nav tabs -->
                <div style="text-align: center">
                    {% include 'imanager/_items.html' %}
                </div>
            </div><!--//tabbed-area-->

        </div><!--//container-->
    </div><!--//features-->
{% endblock %}

app/templates/imanager/itemregistrate.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% set active_page = "itemregistrate" %}
{% block title %}Simian CI - 添加物品{% endblock %}

{% block page_content %}
    <h1 class="lead-title text-center text-lg-left">Simian CI - MANAGE THINGS</h1>
    <p class="lead-subtitle text-center text-lg-left">管理您的个人信息</p>
    <div class="col-md-4" >
        {{ wtf.quick_form(form) }}
    </div>
{% endblock %}

{% block page_content2 %}
    <h1 class="lead-title text-center text-lg-left">Simian CI - MANAGE THINGS</h1>
    <p class="lead-subtitle text-center text-lg-left">管理您的个人信息</p>
    <div class="col-md-4" >
        {{ wtf.quick_form(form) }}
    </div>
{% endblock %}